version: '3'
services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - "80:8080"
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network

  mongo:
    container_name: mongo
    env_file: .env
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
